### ISSUE TITLE
First Time Setup - Reach RS+ and Reach M+

### ISSUE THREAD

**Issue by Yey007** [cornellev/localization-sp24#2]
Need to at least connect to these via the app.

**Comment by Yey007** [comment]
Need to email Reach, probably. Support needed from Jason.

**Comment by Yey007** [comment]
Email sent!

**Comment by ethanuppal** [comment]
Battery is potentially dead.

**Comment by Yey007** [comment]
No support from Reach. Waiting on Rachel to open the Reach RS+ and see if we can get it working.
